apiVersion: apps/v1
kind: Deployment
metadata:
  name: i-love-me-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i-love-me-service
  template:
    metadata:
      labels:
        app: i-love-me-service
    spec:
      containers:
        - name: app
          image: jelkand.azurecr.io/i-love-me-service:0678ea23bc3ecce0acbde39389ee4e16dcc48e51
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: i-love-me-service
spec:
  selector:
    app: i-love-me-service
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: i-love-me-service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: i-love-me-service
              servicePort: 80
            path: /(.*)
